package com.example.backupmanager;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Set;
import static com.example.backupmanager.Compat.isBlank;
import static com.example.backupmanager.Compat.setOf;

/** Normalizes OceanProtect copies without allowing one malformed copy to abort a page. */
final class OceanProtectParser {
    static final String MONTHLY = "monthly";
    static final String YEARLY = "yearly";

    private static final ZoneId ZONE = ZoneId.of("Asia/Shanghai");

    private OceanProtectParser() {}

    enum State {
        PARSED,
        IGNORED,
        AMBIGUOUS
    }

    static final class ParseResult {
        private final State state;
        private final String kind;
        private final String slaName;
        private final PlatformParser.Normalized normalized;
        private final String reason;

        private ParseResult(State state, String kind, String slaName,
                            PlatformParser.Normalized normalized, String reason) {
            this.state = state;
            this.kind = kind;
            this.slaName = slaName;
            this.normalized = normalized;
            this.reason = reason;
        }

        static ParseResult parsed(String kind, String slaName, PlatformParser.Normalized normalized) {
            return new ParseResult(State.PARSED, kind, slaName, normalized, "");
        }

        static ParseResult ignored(String reason) {
            return new ParseResult(State.IGNORED, null, null, null, reason);
        }

        static ParseResult ambiguous(String slaName, String reason) {
            return new ParseResult(State.AMBIGUOUS, null, slaName, null, reason);
        }

        boolean parsed() {
            return state == State.PARSED;
        }

        boolean ignored() {
            return state == State.IGNORED;
        }

        boolean ambiguous() {
            return state == State.AMBIGUOUS;
        }

        State state() { return state; }
        String kind() { return kind; }
        String slaName() { return slaName; }
        PlatformParser.Normalized normalized() { return normalized; }
        String reason() { return reason; }
    }

    /**
     * Parses one item returned by {@code GET /v1/copies}.
     * Missing or malformed item data is represented as {@link State#IGNORED}.
     */
    static ParseResult parse(JsonNode row, ObjectMapper mapper) {
        if (row == null || !row.isObject()) return ParseResult.ignored("copy is not an object");

        String resourceName = text(row, "resource_name");
        String uuid = text(row, "uuid");
        String timestamp = text(row, "display_timestamp");
        String status = text(row, "status");
        String slaName = text(row, "sla_name");
        String generatedBy = text(row, "generated_by");
        if (isBlank(resourceName) || isBlank(uuid) || isBlank(timestamp)
                || isBlank(status) || isBlank(slaName)) {
            return ParseResult.ignored(
                "copy is missing resource_name, uuid, display_timestamp, status, or sla_name");
        }
        if (!generatedBy.equalsIgnoreCase("sla") && !generatedBy.equalsIgnoreCase("backup")) {
            return ParseResult.ignored("copy was not generated by an SLA backup");
        }
        if (booleanValue(row, "is_archived") || booleanValue(row, "is_replicated")) {
            return ParseResult.ignored("archived or replicated copy is not a primary backup");
        }

        JsonNode properties = row.get("sla_properties");
        SlaKinds analysis = analyzeSla(properties, mapper);
        if (!analysis.valid()) return ParseResult.ignored("sla_properties is missing or malformed");

        if (analysis.kinds().isEmpty()) {
            return ParseResult.ignored("SLA has no month or year schedule");
        }
        if (analysis.backupScheduleCount() != 1 || analysis.kinds().size() != 1) {
            return ParseResult.ambiguous(slaName,
                "SLA contains multiple backup schedules, so the copy schedule cannot be determined");
        }
        String kind = analysis.kinds().iterator().next();

        Instant eventTime;
        try {
            eventTime = parseTime(timestamp);
        } catch (DateTimeParseException error) {
            return ParseResult.ignored("display_timestamp is invalid");
        }

        String normalizedStatus = status.equalsIgnoreCase("available") ? "successed" : status;
        PlatformParser.Normalized normalized = new PlatformParser.Normalized(
            resourceName,
            uuid,
            eventTime.atZone(ZONE).toLocalDate(),
            false,
            eventTime,
            normalizedStatus,
            row.toString()
        );
        return ParseResult.parsed(kind, slaName, normalized);
    }

    /**
     * Returns database backup kinds declared by an SLA's
     * {@code policy_list[].schedule.trigger_action} values.
     */
    static Set<String> kindsFromSla(JsonNode sla, ObjectMapper mapper) {
        SlaKinds analysis = analyzeSla(sla, mapper);
        return analysis.valid() ? analysis.kinds() : setOf();
    }

    private static SlaKinds analyzeSla(JsonNode source, ObjectMapper mapper) {
        if (source == null || source.isNull() || source.isMissingNode()) {
            return new SlaKinds(false, setOf(), 0);
        }

        JsonNode sla = source;
        try {
            if (sla.isTextual()) {
                String json = sla.asText().trim();
                if (json.isEmpty()) return new SlaKinds(false, setOf(), 0);
                sla = mapper.readTree(json);
            }
        } catch (Exception error) {
            return new SlaKinds(false, setOf(), 0);
        }
        if (sla == null || !sla.isObject()) return new SlaKinds(false, setOf(), 0);

        JsonNode policies = sla.get("policy_list");
        if (policies == null || !policies.isArray()) return new SlaKinds(false, setOf(), 0);

        Set<String> kinds = new LinkedHashSet<>();
        int backupScheduleCount = 0;
        for (JsonNode policy : policies) {
            if (!isBackupPolicy(policy)) continue;
            JsonNode schedule = policy.get("schedule");
            if (schedule == null || !schedule.isObject() || schedule.size() == 0) continue;
            backupScheduleCount++;
            String action = text(schedule, "trigger_action").toLowerCase(Locale.ROOT);
            if (action.equals("month")) kinds.add(MONTHLY);
            if (action.equals("year")) kinds.add(YEARLY);
        }
        return new SlaKinds(true, Collections.unmodifiableSet(kinds), backupScheduleCount);
    }

    private static boolean isBackupPolicy(JsonNode policy) {
        if (policy == null || !policy.isObject()) return false;
        String type = text(policy, "type");
        if (!isBlank(type) && !type.equalsIgnoreCase("backup")) return false;
        String action = text(policy, "action");
        return !action.equalsIgnoreCase("replication") && !action.equalsIgnoreCase("archiving");
    }

    private static boolean booleanValue(JsonNode node, String field) {
        if (node == null || !node.isObject()) return false;
        JsonNode value = node.get(field);
        if (value == null || value.isNull()) return false;
        if (value.isBoolean()) return value.booleanValue();
        return value.isTextual() && value.asText().trim().equalsIgnoreCase("true");
    }

    private static String text(JsonNode node, String field) {
        if (node == null || !node.isObject()) return "";
        JsonNode value = node.get(field);
        return value == null || value.isNull() ? "" : value.asText("").trim();
    }

    private static Instant parseTime(String text) {
        String normalized = text.trim().replace(' ', 'T');
        try {
            return Instant.parse(normalized);
        } catch (DateTimeParseException ignored) {
            // Try timestamps carrying a non-Z offset next.
        }
        try {
            return OffsetDateTime.parse(normalized).toInstant();
        } catch (DateTimeParseException ignored) {
            // OceanProtect installations may return a local timestamp without an offset.
        }
        return LocalDateTime.parse(normalized).atZone(ZONE).toInstant();
    }

    private static final class SlaKinds {
        private final boolean valid;
        private final Set<String> kinds;
        private final int backupScheduleCount;

        private SlaKinds(boolean valid, Set<String> kinds, int backupScheduleCount) {
            this.valid = valid;
            this.kinds = kinds;
            this.backupScheduleCount = backupScheduleCount;
        }

        boolean valid() { return valid; }
        Set<String> kinds() { return kinds; }
        int backupScheduleCount() { return backupScheduleCount; }
    }
}
