CREATE TABLE app_user (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'VIEWER',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE database_catalog (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  monitor_from DATE NOT NULL,
  monitor_from_auto BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE backup_record (
  id BIGSERIAL PRIMARY KEY,
  database_id BIGINT NOT NULL REFERENCES database_catalog(id),
  kind VARCHAR(10) NOT NULL,
  external_id VARCHAR(255) NOT NULL,
  backup_date DATE NOT NULL,
  date_inferred BOOLEAN NOT NULL DEFAULT FALSE,
  event_time TIMESTAMPTZ NOT NULL,
  status VARCHAR(64) NOT NULL,
  raw_data TEXT NOT NULL,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_backup_source UNIQUE(kind, external_id)
);
CREATE INDEX idx_backup_database_date ON backup_record(database_id, kind, backup_date DESC);
CREATE INDEX idx_backup_date ON backup_record(backup_date DESC);

CREATE TABLE backup_rule (
  id BIGSERIAL PRIMARY KEY,
  kind VARCHAR(10) NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL,
  grace_days INTEGER NOT NULL DEFAULT 2,
  retention_days INTEGER,
  note VARCHAR(255) NOT NULL DEFAULT ''
);
INSERT INTO backup_rule(kind, enabled, grace_days, retention_days, note) VALUES
  ('daily', TRUE, 2, 7, '每天备份；保留7天'),
  ('monthly', FALSE, 2, 365, '每月1日备份；接口待接入'),
  ('yearly', FALSE, 2, NULL, '每年12月31日备份；永久保留；接口待接入');

CREATE TABLE sync_run (
  id BIGSERIAL PRIMARY KEY,
  kind VARCHAR(10) NOT NULL,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  status VARCHAR(20) NOT NULL,
  fetched_count INTEGER NOT NULL DEFAULT 0,
  saved_count INTEGER NOT NULL DEFAULT 0,
  error TEXT NOT NULL DEFAULT ''
);

CREATE TABLE SPRING_SESSION (
  PRIMARY_ID CHAR(36) NOT NULL,
  SESSION_ID CHAR(36) NOT NULL,
  CREATION_TIME BIGINT NOT NULL,
  LAST_ACCESS_TIME BIGINT NOT NULL,
  MAX_INACTIVE_INTERVAL INT NOT NULL,
  EXPIRY_TIME BIGINT NOT NULL,
  PRINCIPAL_NAME VARCHAR(100),
  CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
CREATE TABLE SPRING_SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES BYTEA NOT NULL,
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
  CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
